### ISSUE TITLE
Problem with ipsecNumber

### ISSUE THREAD

**Issue by acejacek** [jessedp/vim-ipsec#2]
Something wrong with the regexp, because it doesn't recognizes number parameters correctly.
`syn match   ipsecNumber contained /\d\+\(\.\d\+\)\=/`

Workaround is to simplify the regexp :
`syn match   ipsecNumber contained /=\d\+/`

**Comment by jessedp** [comment]
Hmm. The ones I've tested this with seem ok - would you mind providing an example or two of something that should match?

**Comment by acejacek** [comment]
Fixed with issue #1. I wrongly assigned "keyingtries" to ipsecNumber and it created problems.
